---
apikey: "fbd76c92-3061-47c9-98d8-68975926a27b"
urlDataBase: "jdbc:mysql://mysql-iitzwolfyy.alwaysdata.net:3306/iitzwolfyy_stats_hypixel"
usernameDataBase: "333319"
passwordDataBase: "}ZVZe7tECD+h>_&"
