---
apikey: "d0212c80-68bf-4fe8-a0ae-ccb279383427"
urlDataBase: "jdbc:mysql://mysql-iitzwolfyy.alwaysdata.net:3306/iitzwolfyy_stats_hypixel"
usernameDataBase: "333319"
passwordDataBase: "}ZVZe7tECD+h>_&"
